Blog:
    pattern:  /blog
    defaults: { _controller: "Application:Blog:index"}
    
BlogView:
    pattern:  /blog/{postID}/{title}
    defaults: { _controller: "Application:Blog:view"}
    
BlogTagView:
    pattern:  /blog/tag/{tagID}/{title}
    defaults: { _controller: "Application:Blog:tagview"}
    
BlogGetPopular:
    pattern:  /blog/get_popular_tags
    defaults: { _controller: "Application:Blog:getPopularTags"}

BlogGetRecentComments:
    pattern:  /blog/get_recent_comments
    defaults: { _controller: "Application:Blog:getRecentComments"}
    
BlogGetRelatedPosts:
    pattern:  /blog/get_related_posts
    defaults: { _controller: "Application:Blog:getRelatedPosts"}
    requirements:
        _method: POST
        