fields:
	first_name:
		type: text
		label: First Name
		size: 30
	email:
		type: text
		label: Email
		size: 30
	password:
		type: password
		label: Password
		size: 30
	submit:
		type: submit
		label: Login
		value: Login
rules:
	email:
		type: required
		message: Email cannot be blank
	password:
		type: required
		message: Password cannot be blank
	first_name:
		type: maxlength
		message: Your name must be no more than 25 characters
		value: 25
