Homepage:
    pattern:  /
    defaults: { _controller: "Application:Index:index"}
    
Download:
    pattern:  /download/{type}
    defaults: { _controller: "Application:Index:download"}

About:
    pattern:  /about
    defaults: { _controller: "Application:Index:about"}

Community:
    pattern:  /community
    defaults: { _controller: "Application:Index:community"}
    
Contributors:
    pattern:  /contributors
    defaults: { _controller: "Application:Index:contributors"}
    
Projects:
    pattern:  /projects
    defaults: { _controller: "Application:Index:projects"}
    
    